seq2seq: {
    start_token: '<',
    end_token: '>',
    batch_size: 64,
    epochs: 250,
    latent_dim: 256,
    num_samples: 100000,
    n: 10,
    snapshot_path: "snapshots.txt"
}

text: {
    data: 'nietzsche',
    step: 3,
    epochs: 10,
    n_samples: 10000,
    n_results: 400,
    layer_sizes: [512, 640, 256],
    dropouts: [0.2, 0.3, 0.0],
    maxlens: [10, 50, 100],
    snapshot_path: "../results/snapshot_books.txt"
}

names: {
    action: 'generate',
    data: 'names',
    step: 1,
    epochs: 1,
    n_samples: 10000,
    n_results: 2,
    layer_sizes: [128], #[64, 128, 192],
    bidirectional: False,
    dropouts: [0.05],
    maxlens: [3],
    snapshot_path: "../results/names",
    examples: {
               'n': 2,
               'diversities': [0.50, 0.75],
               'names_name': "."
              },
    generate: {
               'n': 5000,
               'diversities': [0.75],
               'model_name': "../results/names_01_model-l128-d05-q10.h5",
               'names_name': "namen.txt"
              }
}

